// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getNextDeliveryVersionForSession = `-- name: GetNextDeliveryVersionForSession :one
SELECT COALESCE(MAX(version), 0)::bigint + 1 AS next_version
FROM deliveries
WHERE session_id = $1
`

func (q *Queries) GetNextDeliveryVersionForSession(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextDeliveryVersionForSession, sessionID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO deliveries (
  id,
  session_id,
  version,
  status,
  created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  now()
)
`

type InsertDeliveryParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	Version   int32     `db:"version" json:"version"`
	Status    string    `db:"status" json:"status"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.ID,
		arg.SessionID,
		arg.Version,
		arg.Status,
	)
	return err
}
