// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: final_photos.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countFinalPhotosBySessionID = `-- name: CountFinalPhotosBySessionID :one
SELECT COUNT(*)::bigint
FROM final_photos
WHERE session_id = $1
`

func (q *Queries) CountFinalPhotosBySessionID(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFinalPhotosBySessionID, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getFinalPhotoByIDAndSessionID = `-- name: GetFinalPhotoByIDAndSessionID :one
SELECT
  id,
  session_id,
  photo_id,
  final_key,
  final_size_bytes
FROM final_photos
WHERE id = $1
  AND session_id = $2
`

type GetFinalPhotoByIDAndSessionIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

type GetFinalPhotoByIDAndSessionIDRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID        uuid.UUID `db:"photo_id" json:"photo_id"`
	FinalKey       string    `db:"final_key" json:"final_key"`
	FinalSizeBytes *int64    `db:"final_size_bytes" json:"final_size_bytes"`
}

func (q *Queries) GetFinalPhotoByIDAndSessionID(ctx context.Context, arg GetFinalPhotoByIDAndSessionIDParams) (GetFinalPhotoByIDAndSessionIDRow, error) {
	row := q.db.QueryRow(ctx, getFinalPhotoByIDAndSessionID, arg.ID, arg.SessionID)
	var i GetFinalPhotoByIDAndSessionIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PhotoID,
		&i.FinalKey,
		&i.FinalSizeBytes,
	)
	return i, err
}

const hasFinalPhotoForSessionPhoto = `-- name: HasFinalPhotoForSessionPhoto :one
SELECT EXISTS (
  SELECT 1
  FROM final_photos
  WHERE session_id = $1
    AND photo_id = $2
) AS ok
`

type HasFinalPhotoForSessionPhotoParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
}

func (q *Queries) HasFinalPhotoForSessionPhoto(ctx context.Context, arg HasFinalPhotoForSessionPhotoParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasFinalPhotoForSessionPhoto, arg.SessionID, arg.PhotoID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const insertFinalPhoto = `-- name: InsertFinalPhoto :exec
INSERT INTO final_photos (
  id,
  session_id,
  photo_id,
  final_key,
  final_size_bytes,
  created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  now()
)
`

type InsertFinalPhotoParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID        uuid.UUID `db:"photo_id" json:"photo_id"`
	FinalKey       string    `db:"final_key" json:"final_key"`
	FinalSizeBytes *int64    `db:"final_size_bytes" json:"final_size_bytes"`
}

func (q *Queries) InsertFinalPhoto(ctx context.Context, arg InsertFinalPhotoParams) error {
	_, err := q.db.Exec(ctx, insertFinalPhoto,
		arg.ID,
		arg.SessionID,
		arg.PhotoID,
		arg.FinalKey,
		arg.FinalSizeBytes,
	)
	return err
}

const updateFinalPhotoSize = `-- name: UpdateFinalPhotoSize :execrows
UPDATE final_photos
SET final_size_bytes = $1
WHERE id = $2
  AND session_id = $3
`

type UpdateFinalPhotoSizeParams struct {
	FinalSizeBytes *int64    `db:"final_size_bytes" json:"final_size_bytes"`
	ID             uuid.UUID `db:"id" json:"id"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) UpdateFinalPhotoSize(ctx context.Context, arg UpdateFinalPhotoSizeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFinalPhotoSize, arg.FinalSizeBytes, arg.ID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
