// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: galerries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGallery = `-- name: CreateGallery :one
INSERT INTO galleries (
    id,
    photographer_id,
    title,
    slug,
    is_public
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    photographer_id,
    title,
    slug,
    is_public,
    created_at
`

type CreateGalleryParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title          string    `db:"title" json:"title"`
	Slug           string    `db:"slug" json:"slug"`
	IsPublic       bool      `db:"is_public" json:"is_public"`
}

func (q *Queries) CreateGallery(ctx context.Context, arg CreateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, createGallery,
		arg.ID,
		arg.PhotographerID,
		arg.Title,
		arg.Slug,
		arg.IsPublic,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const createGalleryPhotoFromCompletedUpload = `-- name: CreateGalleryPhotoFromCompletedUpload :one
INSERT INTO gallery_photos (
    id,
    gallery_id,
    image_key,
    width,
    height,
    sort_order
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE(MAX(sort_order) + 1, 0)
FROM gallery_photos
WHERE gallery_id = $2
RETURNING
    id,
    gallery_id,
    image_key,
    width,
    height,
    sort_order,
    created_at
`

type CreateGalleryPhotoFromCompletedUploadParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	GalleryID uuid.UUID `db:"gallery_id" json:"gallery_id"`
	ImageKey  string    `db:"image_key" json:"image_key"`
	Width     *int32    `db:"width" json:"width"`
	Height    *int32    `db:"height" json:"height"`
}

func (q *Queries) CreateGalleryPhotoFromCompletedUpload(ctx context.Context, arg CreateGalleryPhotoFromCompletedUploadParams) (GalleryPhoto, error) {
	row := q.db.QueryRow(ctx, createGalleryPhotoFromCompletedUpload,
		arg.ID,
		arg.GalleryID,
		arg.ImageKey,
		arg.Width,
		arg.Height,
	)
	var i GalleryPhoto
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.ImageKey,
		&i.Width,
		&i.Height,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGallery = `-- name: DeleteGallery :exec
DELETE FROM galleries
WHERE id = $1
  AND photographer_id = $2
`

type DeleteGalleryParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

func (q *Queries) DeleteGallery(ctx context.Context, arg DeleteGalleryParams) error {
	_, err := q.db.Exec(ctx, deleteGallery, arg.ID, arg.PhotographerID)
	return err
}

const deleteGalleryPhoto = `-- name: DeleteGalleryPhoto :exec
DELETE FROM gallery_photos gp
USING galleries g
WHERE gp.gallery_id = g.id
  AND gp.id = $1
  AND gp.gallery_id = $2
  AND g.photographer_id = $3
`

type DeleteGalleryPhotoParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	GalleryID      uuid.UUID `db:"gallery_id" json:"gallery_id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

func (q *Queries) DeleteGalleryPhoto(ctx context.Context, arg DeleteGalleryPhotoParams) error {
	_, err := q.db.Exec(ctx, deleteGalleryPhoto, arg.ID, arg.GalleryID, arg.PhotographerID)
	return err
}

const getGalleryByIDForOwner = `-- name: GetGalleryByIDForOwner :one
SELECT
    g.id,
    g.photographer_id,
    g.title,
    g.slug,
    g.is_public,
    g.created_at,
    COALESCE(stats.photo_count, 0)::int AS photo_count,
    COALESCE(cover.image_key, '')::text AS cover_image_key
FROM galleries g
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS photo_count
    FROM gallery_photos gp
    WHERE gp.gallery_id = g.id
      AND gp.width > 0
      AND gp.height > 0
) stats ON true
LEFT JOIN LATERAL (
    SELECT gp.image_key
    FROM gallery_photos gp
    WHERE gp.gallery_id = g.id
      AND gp.width > 0
      AND gp.height > 0
    ORDER BY gp.sort_order ASC, gp.created_at ASC
    LIMIT 1
) cover ON true
WHERE g.id = $1
  AND g.photographer_id = $2
`

type GetGalleryByIDForOwnerParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

type GetGalleryByIDForOwnerRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title          string    `db:"title" json:"title"`
	Slug           string    `db:"slug" json:"slug"`
	IsPublic       bool      `db:"is_public" json:"is_public"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	PhotoCount     int32     `db:"photo_count" json:"photo_count"`
	CoverImageKey  string    `db:"cover_image_key" json:"cover_image_key"`
}

func (q *Queries) GetGalleryByIDForOwner(ctx context.Context, arg GetGalleryByIDForOwnerParams) (GetGalleryByIDForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getGalleryByIDForOwner, arg.ID, arg.PhotographerID)
	var i GetGalleryByIDForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedAt,
		&i.PhotoCount,
		&i.CoverImageKey,
	)
	return i, err
}

const getGalleryPhotoForOwner = `-- name: GetGalleryPhotoForOwner :one
SELECT
    gp.id,
    gp.gallery_id,
    gp.image_key,
    gp.width,
    gp.height,
    gp.sort_order,
    gp.created_at
FROM gallery_photos gp
JOIN galleries g
    ON g.id = gp.gallery_id
WHERE gp.id = $1
  AND gp.gallery_id = $2
  AND g.photographer_id = $3
`

type GetGalleryPhotoForOwnerParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	GalleryID      uuid.UUID `db:"gallery_id" json:"gallery_id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

func (q *Queries) GetGalleryPhotoForOwner(ctx context.Context, arg GetGalleryPhotoForOwnerParams) (GalleryPhoto, error) {
	row := q.db.QueryRow(ctx, getGalleryPhotoForOwner, arg.ID, arg.GalleryID, arg.PhotographerID)
	var i GalleryPhoto
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.ImageKey,
		&i.Width,
		&i.Height,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicGalleryByUsernameAndSlug = `-- name: GetPublicGalleryByUsernameAndSlug :one
SELECT
    g.id,
    g.photographer_id,
    g.title,
    g.slug,
    g.is_public,
    g.created_at
FROM galleries g
JOIN photographer_profiles pp
    ON pp.user_id = g.photographer_id
WHERE pp.username = $1
  AND g.slug = $2
  AND g.is_public = true
`

type GetPublicGalleryByUsernameAndSlugParams struct {
	Username string `db:"username" json:"username"`
	Slug     string `db:"slug" json:"slug"`
}

func (q *Queries) GetPublicGalleryByUsernameAndSlug(ctx context.Context, arg GetPublicGalleryByUsernameAndSlugParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, getPublicGalleryByUsernameAndSlug, arg.Username, arg.Slug)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicPhotographerByUsername = `-- name: GetPublicPhotographerByUsername :one
SELECT
    user_id,
    username,
    display_name,
    bio,
    social_links,
    created_at,
    updated_at
FROM photographer_profiles
WHERE username = $1
`

func (q *Queries) GetPublicPhotographerByUsername(ctx context.Context, username string) (PhotographerProfile, error) {
	row := q.db.QueryRow(ctx, getPublicPhotographerByUsername, username)
	var i PhotographerProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGalleriesByOwner = `-- name: ListGalleriesByOwner :many
SELECT
    g.id,
    g.photographer_id,
    g.title,
    g.slug,
    g.is_public,
    g.created_at,
    COALESCE(stats.photo_count, 0)::int AS photo_count,
    COALESCE(cover.image_key, '')::text AS cover_image_key
FROM galleries g
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS photo_count
    FROM gallery_photos gp
    WHERE gp.gallery_id = g.id
      AND gp.width > 0
      AND gp.height > 0
) stats ON true
LEFT JOIN LATERAL (
    SELECT gp.image_key
    FROM gallery_photos gp
    WHERE gp.gallery_id = g.id
      AND gp.width > 0
      AND gp.height > 0
    ORDER BY gp.sort_order ASC, gp.created_at ASC
    LIMIT 1
) cover ON true
WHERE g.photographer_id = $1
ORDER BY g.created_at DESC
`

type ListGalleriesByOwnerRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title          string    `db:"title" json:"title"`
	Slug           string    `db:"slug" json:"slug"`
	IsPublic       bool      `db:"is_public" json:"is_public"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	PhotoCount     int32     `db:"photo_count" json:"photo_count"`
	CoverImageKey  string    `db:"cover_image_key" json:"cover_image_key"`
}

func (q *Queries) ListGalleriesByOwner(ctx context.Context, photographerID uuid.UUID) ([]ListGalleriesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listGalleriesByOwner, photographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGalleriesByOwnerRow{}
	for rows.Next() {
		var i ListGalleriesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Title,
			&i.Slug,
			&i.IsPublic,
			&i.CreatedAt,
			&i.PhotoCount,
			&i.CoverImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleryPhotosForOwner = `-- name: ListGalleryPhotosForOwner :many
SELECT
    gp.id,
    gp.gallery_id,
    gp.image_key,
    gp.width,
    gp.height,
    gp.sort_order,
    gp.created_at
FROM gallery_photos gp
JOIN galleries g
    ON g.id = gp.gallery_id
WHERE gp.gallery_id = $1
  AND g.photographer_id = $2
ORDER BY gp.sort_order ASC, gp.created_at ASC
`

type ListGalleryPhotosForOwnerParams struct {
	GalleryID      uuid.UUID `db:"gallery_id" json:"gallery_id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

func (q *Queries) ListGalleryPhotosForOwner(ctx context.Context, arg ListGalleryPhotosForOwnerParams) ([]GalleryPhoto, error) {
	rows, err := q.db.Query(ctx, listGalleryPhotosForOwner, arg.GalleryID, arg.PhotographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GalleryPhoto{}
	for rows.Next() {
		var i GalleryPhoto
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.ImageKey,
			&i.Width,
			&i.Height,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGalleriesByPhotographerID = `-- name: ListPublicGalleriesByPhotographerID :many
SELECT
    g.id,
    g.photographer_id,
    g.title,
    g.slug,
    g.is_public,
    g.created_at,
    COALESCE(stats.photo_count, 0)::int AS photo_count,
    COALESCE(cover.image_key, '')::text AS cover_image_key
FROM galleries g
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS photo_count
    FROM gallery_photos gp
    WHERE gp.gallery_id = g.id
      AND gp.width > 0
      AND gp.height > 0
) stats ON true
LEFT JOIN LATERAL (
    SELECT gp.image_key
    FROM gallery_photos gp
    WHERE gp.gallery_id = g.id
      AND gp.width > 0
      AND gp.height > 0
    ORDER BY gp.sort_order ASC, gp.created_at ASC
    LIMIT 1
) cover ON true
WHERE g.photographer_id = $1
  AND g.is_public = true
ORDER BY g.created_at DESC
`

type ListPublicGalleriesByPhotographerIDRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title          string    `db:"title" json:"title"`
	Slug           string    `db:"slug" json:"slug"`
	IsPublic       bool      `db:"is_public" json:"is_public"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	PhotoCount     int32     `db:"photo_count" json:"photo_count"`
	CoverImageKey  string    `db:"cover_image_key" json:"cover_image_key"`
}

func (q *Queries) ListPublicGalleriesByPhotographerID(ctx context.Context, photographerID uuid.UUID) ([]ListPublicGalleriesByPhotographerIDRow, error) {
	rows, err := q.db.Query(ctx, listPublicGalleriesByPhotographerID, photographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicGalleriesByPhotographerIDRow{}
	for rows.Next() {
		var i ListPublicGalleriesByPhotographerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Title,
			&i.Slug,
			&i.IsPublic,
			&i.CreatedAt,
			&i.PhotoCount,
			&i.CoverImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGalleryPhotos = `-- name: ListPublicGalleryPhotos :many
SELECT
    id,
    gallery_id,
    image_key,
    width,
    height,
    sort_order,
    created_at
FROM gallery_photos
WHERE gallery_id = $1
  AND width > 0
  AND height > 0
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListPublicGalleryPhotos(ctx context.Context, galleryID uuid.UUID) ([]GalleryPhoto, error) {
	rows, err := q.db.Query(ctx, listPublicGalleryPhotos, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GalleryPhoto{}
	for rows.Next() {
		var i GalleryPhoto
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.ImageKey,
			&i.Width,
			&i.Height,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGallery = `-- name: UpdateGallery :one
UPDATE galleries
SET
    title = $3,
    slug = $4,
    is_public = $5
WHERE id = $1
  AND photographer_id = $2
RETURNING
    id,
    photographer_id,
    title,
    slug,
    is_public,
    created_at
`

type UpdateGalleryParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title          string    `db:"title" json:"title"`
	Slug           string    `db:"slug" json:"slug"`
	IsPublic       bool      `db:"is_public" json:"is_public"`
}

func (q *Queries) UpdateGallery(ctx context.Context, arg UpdateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, updateGallery,
		arg.ID,
		arg.PhotographerID,
		arg.Title,
		arg.Slug,
		arg.IsPublic,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}
