// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDueJobs = `-- name: ClaimDueJobs :many
WITH picked AS (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
      AND next_run_at <= now()
      AND attempts < max_attempts
    ORDER BY next_run_at, created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET
    status = 'running',
    locked_at = now(),
    locked_by = $1,
    attempts = attempts + 1,
    updated_at = now(),
    last_error = NULL
WHERE id IN (SELECT id FROM picked)
RETURNING
    id,
    type,
    status,
    payload,
    attempts,
    max_attempts,
    next_run_at,
    locked_at,
    locked_by,
    last_error,
    created_at,
    updated_at
`

type ClaimDueJobsParams struct {
	LockedBy   *string `db:"locked_by" json:"locked_by"`
	LimitCount int32   `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ClaimDueJobs(ctx context.Context, arg ClaimDueJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, arg.LockedBy, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRunAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs (
    id,
    type,
    payload,
    max_attempts
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type EnqueueJobParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Type        string    `db:"type" json:"type"`
	Payload     []byte    `db:"payload" json:"payload"`
	MaxAttempts int32     `db:"max_attempts" json:"max_attempts"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.MaxAttempts,
	)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :execrows
UPDATE jobs
SET
    status = 'failed',
    locked_at = NULL,
    locked_by = NULL,
    last_error = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'running'
`

type MarkJobFailedParams struct {
	LastError *string   `db:"last_error" json:"last_error"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markJobFailed, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobRetry = `-- name: MarkJobRetry :execrows
UPDATE jobs
SET
    status = 'pending',
    locked_at = NULL,
    locked_by = NULL,
    last_error = $1,
    next_run_at = $2,
    updated_at = now()
WHERE id = $3
  AND status = 'running'
`

type MarkJobRetryParams struct {
	LastError *string   `db:"last_error" json:"last_error"`
	NextRunAt time.Time `db:"next_run_at" json:"next_run_at"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkJobRetry(ctx context.Context, arg MarkJobRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, markJobRetry, arg.LastError, arg.NextRunAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobSucceeded = `-- name: MarkJobSucceeded :execrows
UPDATE jobs
SET
    status = 'succeeded',
    locked_at = NULL,
    locked_by = NULL,
    last_error = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'running'
`

func (q *Queries) MarkJobSucceeded(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markJobSucceeded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
