// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs (
    id,
    type,
    payload,
    max_attempts
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type EnqueueJobParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Type        string    `db:"type" json:"type"`
	Payload     []byte    `db:"payload" json:"payload"`
	MaxAttempts int32     `db:"max_attempts" json:"max_attempts"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.MaxAttempts,
	)
	return err
}
