// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Delivery struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	SessionID    uuid.UUID  `db:"session_id" json:"session_id"`
	Version      int32      `db:"version" json:"version"`
	Status       string     `db:"status" json:"status"`
	ZipKey       *string    `db:"zip_key" json:"zip_key"`
	ZipSizeBytes *int64     `db:"zip_size_bytes" json:"zip_size_bytes"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	GeneratedAt  *time.Time `db:"generated_at" json:"generated_at"`
}

type FinalPhoto struct {
	ID             uuid.UUID `db:"id" json:"id"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID        uuid.UUID `db:"photo_id" json:"photo_id"`
	FinalKey       string    `db:"final_key" json:"final_key"`
	FinalSizeBytes *int64    `db:"final_size_bytes" json:"final_size_bytes"`
	Width          *int32    `db:"width" json:"width"`
	Height         *int32    `db:"height" json:"height"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type Gallery struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title          string    `db:"title" json:"title"`
	Slug           string    `db:"slug" json:"slug"`
	IsPublic       bool      `db:"is_public" json:"is_public"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type GalleryPhoto struct {
	ID        uuid.UUID `db:"id" json:"id"`
	GalleryID uuid.UUID `db:"gallery_id" json:"gallery_id"`
	ImageKey  string    `db:"image_key" json:"image_key"`
	Width     *int32    `db:"width" json:"width"`
	Height    *int32    `db:"height" json:"height"`
	SortOrder int32     `db:"sort_order" json:"sort_order"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Job struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Type        string     `db:"type" json:"type"`
	Status      string     `db:"status" json:"status"`
	Payload     []byte     `db:"payload" json:"payload"`
	Attempts    int32      `db:"attempts" json:"attempts"`
	MaxAttempts int32      `db:"max_attempts" json:"max_attempts"`
	NextRunAt   time.Time  `db:"next_run_at" json:"next_run_at"`
	LockedAt    *time.Time `db:"locked_at" json:"locked_at"`
	LockedBy    *string    `db:"locked_by" json:"locked_by"`
	LastError   *string    `db:"last_error" json:"last_error"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
}

type Payment struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	SessionID   uuid.UUID  `db:"session_id" json:"session_id"`
	Method      string     `db:"method" json:"method"`
	Status      string     `db:"status" json:"status"`
	AmountCents int32      `db:"amount_cents" json:"amount_cents"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	PaidAt      *time.Time `db:"paid_at" json:"paid_at"`
}

type PhotographerProfile struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Username    string    `db:"username" json:"username"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Bio         string    `db:"bio" json:"bio"`
	SocialLinks []byte    `db:"social_links" json:"social_links"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Selection struct {
	SessionID  uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID    uuid.UUID `db:"photo_id" json:"photo_id"`
	SelectedAt time.Time `db:"selected_at" json:"selected_at"`
	Note       *string   `db:"note" json:"note"`
}

type Session struct {
	ID              uuid.UUID  `db:"id" json:"id"`
	PhotographerID  uuid.UUID  `db:"photographer_id" json:"photographer_id"`
	Title           string     `db:"title" json:"title"`
	ClientEmail     *string    `db:"client_email" json:"client_email"`
	Status          string     `db:"status" json:"status"`
	BasePriceCents  int32      `db:"base_price_cents" json:"base_price_cents"`
	IncludedCount   int32      `db:"included_count" json:"included_count"`
	ExtraPriceCents int32      `db:"extra_price_cents" json:"extra_price_cents"`
	MinSelectCount  int32      `db:"min_select_count" json:"min_select_count"`
	Currency        string     `db:"currency" json:"currency"`
	PaymentMode     string     `db:"payment_mode" json:"payment_mode"`
	CreatedAt       time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time  `db:"updated_at" json:"updated_at"`
	ClosedAt        *time.Time `db:"closed_at" json:"closed_at"`
	DeleteAfter     *time.Time `db:"delete_after" json:"delete_after"`
}

type SessionAccess struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	SessionID  uuid.UUID  `db:"session_id" json:"session_id"`
	CodeHmac   string     `db:"code_hmac" json:"code_hmac"`
	TokenHmac  string     `db:"token_hmac" json:"token_hmac"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	RevokedAt  *time.Time `db:"revoked_at" json:"revoked_at"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

type SessionPhoto struct {
	ID               uuid.UUID `db:"id" json:"id"`
	SessionID        uuid.UUID `db:"session_id" json:"session_id"`
	OriginalFilename string    `db:"original_filename" json:"original_filename"`
	MimeType         string    `db:"mime_type" json:"mime_type"`
	Width            *int32    `db:"width" json:"width"`
	Height           *int32    `db:"height" json:"height"`
	SourceKey        string    `db:"source_key" json:"source_key"`
	SourceSizeBytes  int64     `db:"source_size_bytes" json:"source_size_bytes"`
	ThumbKey         *string   `db:"thumb_key" json:"thumb_key"`
	ProofKey         *string   `db:"proof_key" json:"proof_key"`
	Status           string    `db:"status" json:"status"`
	WatermarkSeed    int32     `db:"watermark_seed" json:"watermark_seed"`
	CreatedAt        time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID        uuid.UUID `db:"id" json:"id"`
	GoogleSub string    `db:"google_sub" json:"google_sub"`
	Email     string    `db:"email" json:"email"`
	Name      string    `db:"name" json:"name"`
	AvatarUrl *string   `db:"avatar_url" json:"avatar_url"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
