// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getUnpaidPaymentBySessionIDForUpdate = `-- name: GetUnpaidPaymentBySessionIDForUpdate :one
SELECT
  id,
  session_id,
  status,
  amount_cents
FROM payments
WHERE session_id = $1
  AND status = 'unpaid'
FOR UPDATE
`

type GetUnpaidPaymentBySessionIDForUpdateRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	SessionID   uuid.UUID `db:"session_id" json:"session_id"`
	Status      string    `db:"status" json:"status"`
	AmountCents int32     `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) GetUnpaidPaymentBySessionIDForUpdate(ctx context.Context, sessionID uuid.UUID) (GetUnpaidPaymentBySessionIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUnpaidPaymentBySessionIDForUpdate, sessionID)
	var i GetUnpaidPaymentBySessionIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.AmountCents,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :execrows
UPDATE payments
SET
  status = 'paid',
  paid_at = now(),
  updated_at = now()
WHERE id = $1
  AND status = 'unpaid'
`

func (q *Queries) MarkPaymentPaid(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentPaid, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
