// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photograpger_selections.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPhotographerSelectionOverview = `-- name: GetPhotographerSelectionOverview :one
SELECT
    s.id AS session_id,
    s.status AS session_status,
    COUNT(sel.photo_id)::int AS selected_count,

    COALESCE(p.status, '') AS payment_status,
    COALESCE(p.amount_cents, 0)::int AS payment_amount_cents,
    p.paid_at AS payment_paid_at
FROM sessions s
LEFT JOIN selections sel
    ON sel.session_id = s.id
LEFT JOIN LATERAL (
    SELECT
        payments.status,
        payments.amount_cents,
        payments.paid_at
    FROM payments
    WHERE payments.session_id = s.id
    ORDER BY payments.created_at DESC
    LIMIT 1
) p ON true
WHERE s.id = $1
GROUP BY
    s.id,
    s.status,
    p.status,
    p.amount_cents,
    p.paid_at
`

type GetPhotographerSelectionOverviewRow struct {
	SessionID          uuid.UUID  `db:"session_id" json:"session_id"`
	SessionStatus      string     `db:"session_status" json:"session_status"`
	SelectedCount      int32      `db:"selected_count" json:"selected_count"`
	PaymentStatus      string     `db:"payment_status" json:"payment_status"`
	PaymentAmountCents int32      `db:"payment_amount_cents" json:"payment_amount_cents"`
	PaymentPaidAt      *time.Time `db:"payment_paid_at" json:"payment_paid_at"`
}

func (q *Queries) GetPhotographerSelectionOverview(ctx context.Context, id uuid.UUID) (GetPhotographerSelectionOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPhotographerSelectionOverview, id)
	var i GetPhotographerSelectionOverviewRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionStatus,
		&i.SelectedCount,
		&i.PaymentStatus,
		&i.PaymentAmountCents,
		&i.PaymentPaidAt,
	)
	return i, err
}

const listPhotographerSelectedPhotos = `-- name: ListPhotographerSelectedPhotos :many
SELECT
    sp.id AS photo_id,
    sp.original_filename,
    sp.thumb_key,
    COALESCE(sel.note, '') AS note,
    sel.selected_at,

    fp.final_id,
    COALESCE(fp.final_uploaded, false)::bool AS final_uploaded
FROM selections sel
JOIN session_photos sp
    ON sp.id = sel.photo_id
    AND sp.session_id = sel.session_id
LEFT JOIN LATERAL (
    SELECT
        final_photos.id AS final_id,
        (
            final_photos.final_key IS NOT NULL
            AND COALESCE(final_photos.final_size_bytes, 0) > 0
        ) AS final_uploaded
    FROM final_photos
    WHERE final_photos.session_id = sel.session_id
      AND final_photos.photo_id = sel.photo_id
    ORDER BY final_photos.created_at DESC
    LIMIT 1
) fp ON true
WHERE sel.session_id = $1
ORDER BY sel.selected_at ASC, sp.created_at ASC
`

type ListPhotographerSelectedPhotosRow struct {
	PhotoID          uuid.UUID `db:"photo_id" json:"photo_id"`
	OriginalFilename string    `db:"original_filename" json:"original_filename"`
	ThumbKey         *string   `db:"thumb_key" json:"thumb_key"`
	Note             string    `db:"note" json:"note"`
	SelectedAt       time.Time `db:"selected_at" json:"selected_at"`
	FinalID          uuid.UUID `db:"final_id" json:"final_id"`
	FinalUploaded    bool      `db:"final_uploaded" json:"final_uploaded"`
}

func (q *Queries) ListPhotographerSelectedPhotos(ctx context.Context, sessionID uuid.UUID) ([]ListPhotographerSelectedPhotosRow, error) {
	rows, err := q.db.Query(ctx, listPhotographerSelectedPhotos, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhotographerSelectedPhotosRow{}
	for rows.Next() {
		var i ListPhotographerSelectedPhotosRow
		if err := rows.Scan(
			&i.PhotoID,
			&i.OriginalFilename,
			&i.ThumbKey,
			&i.Note,
			&i.SelectedAt,
			&i.FinalID,
			&i.FinalUploaded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
