// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getPhotographerProfileByUserID = `-- name: GetPhotographerProfileByUserID :one
SELECT
    user_id,
    username,
    display_name,
    bio,
    social_links,
    created_at,
    updated_at
FROM photographer_profiles
WHERE user_id = $1
`

func (q *Queries) GetPhotographerProfileByUserID(ctx context.Context, userID uuid.UUID) (PhotographerProfile, error) {
	row := q.db.QueryRow(ctx, getPhotographerProfileByUserID, userID)
	var i PhotographerProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPhotographerProfile = `-- name: UpsertPhotographerProfile :one
INSERT INTO photographer_profiles (
    user_id,
    username,
    display_name,
    bio,
    social_links
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (user_id) DO UPDATE
SET
    username = EXCLUDED.username,
    display_name = EXCLUDED.display_name,
    bio = EXCLUDED.bio,
    social_links = EXCLUDED.social_links,
    updated_at = now()
RETURNING
    user_id,
    username,
    display_name,
    bio,
    social_links,
    created_at,
    updated_at
`

type UpsertPhotographerProfileParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Username    string    `db:"username" json:"username"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Bio         string    `db:"bio" json:"bio"`
	SocialLinks []byte    `db:"social_links" json:"social_links"`
}

func (q *Queries) UpsertPhotographerProfile(ctx context.Context, arg UpsertPhotographerProfileParams) (PhotographerProfile, error) {
	row := q.db.QueryRow(ctx, upsertPhotographerProfile,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.SocialLinks,
	)
	var i PhotographerProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
