// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selections.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countSelectedPhotosWithoutFinal = `-- name: CountSelectedPhotosWithoutFinal :one
SELECT COUNT(*)::bigint
FROM selections s
LEFT JOIN final_photos fp
  ON fp.session_id = s.session_id
 AND fp.photo_id = s.photo_id
WHERE s.session_id = $1
  AND fp.id IS NULL
`

func (q *Queries) CountSelectedPhotosWithoutFinal(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSelectedPhotosWithoutFinal, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSelectionsBySessionID = `-- name: CountSelectionsBySessionID :one
SELECT COUNT(*)::bigint AS selected_count
FROM selections
WHERE session_id = $1
`

func (q *Queries) CountSelectionsBySessionID(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSelectionsBySessionID, sessionID)
	var selected_count int64
	err := row.Scan(&selected_count)
	return selected_count, err
}

const deleteSelection = `-- name: DeleteSelection :execrows
DELETE FROM selections
WHERE session_id = $1
  AND photo_id = $2
`

type DeleteSelectionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
}

func (q *Queries) DeleteSelection(ctx context.Context, arg DeleteSelectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSelection, arg.SessionID, arg.PhotoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionSubmitDataForUpdate = `-- name: GetSessionSubmitDataForUpdate :one
SELECT
  id,
  status,
  base_price_cents,
  included_count,
  extra_price_cents,
  min_select_count,
  currency,
  payment_mode
FROM sessions
WHERE id = $1
FOR UPDATE
`

type GetSessionSubmitDataForUpdateRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Status          string    `db:"status" json:"status"`
	BasePriceCents  int32     `db:"base_price_cents" json:"base_price_cents"`
	IncludedCount   int32     `db:"included_count" json:"included_count"`
	ExtraPriceCents int32     `db:"extra_price_cents" json:"extra_price_cents"`
	MinSelectCount  int32     `db:"min_select_count" json:"min_select_count"`
	Currency        string    `db:"currency" json:"currency"`
	PaymentMode     string    `db:"payment_mode" json:"payment_mode"`
}

func (q *Queries) GetSessionSubmitDataForUpdate(ctx context.Context, id uuid.UUID) (GetSessionSubmitDataForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSessionSubmitDataForUpdate, id)
	var i GetSessionSubmitDataForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.BasePriceCents,
		&i.IncludedCount,
		&i.ExtraPriceCents,
		&i.MinSelectCount,
		&i.Currency,
		&i.PaymentMode,
	)
	return i, err
}

const insertSessionPayment = `-- name: InsertSessionPayment :exec
INSERT INTO payments (
  id,
  session_id,
  method,
  status,
  amount_cents,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  now(),
  now()
)
`

type InsertSessionPaymentParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	SessionID   uuid.UUID `db:"session_id" json:"session_id"`
	Method      string    `db:"method" json:"method"`
	Status      string    `db:"status" json:"status"`
	AmountCents int32     `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) InsertSessionPayment(ctx context.Context, arg InsertSessionPaymentParams) error {
	_, err := q.db.Exec(ctx, insertSessionPayment,
		arg.ID,
		arg.SessionID,
		arg.Method,
		arg.Status,
		arg.AmountCents,
	)
	return err
}

const markSessionWaitingForPayment = `-- name: MarkSessionWaitingForPayment :execrows
UPDATE sessions
SET
  status = 'waiting_for_payment',
  updated_at = now()
WHERE id = $1
  AND status = 'selecting'
`

func (q *Queries) MarkSessionWaitingForPayment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionWaitingForPayment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSelection = `-- name: UpsertSelection :exec
INSERT INTO selections (
    session_id,
    photo_id,
    selected_at,
    note
) VALUES (
    $1,
    $2,
    now(),
    $3
)
ON CONFLICT (session_id, photo_id)
DO UPDATE
SET note = EXCLUDED.note
`

type UpsertSelectionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
	Note      *string   `db:"note" json:"note"`
}

func (q *Queries) UpsertSelection(ctx context.Context, arg UpsertSelectionParams) error {
	_, err := q.db.Exec(ctx, upsertSelection, arg.SessionID, arg.PhotoID, arg.Note)
	return err
}
