// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selections.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteSelection = `-- name: DeleteSelection :execrows
DELETE FROM selections
WHERE session_id = $1
  AND photo_id = $2
`

type DeleteSelectionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
}

func (q *Queries) DeleteSelection(ctx context.Context, arg DeleteSelectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSelection, arg.SessionID, arg.PhotoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSelection = `-- name: UpsertSelection :exec
INSERT INTO selections (
    session_id,
    photo_id,
    selected_at,
    note
) VALUES (
    $1,
    $2,
    now(),
    $3
)
ON CONFLICT (session_id, photo_id)
DO UPDATE
SET note = EXCLUDED.note
`

type UpsertSelectionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
	Note      *string   `db:"note" json:"note"`
}

func (q *Queries) UpsertSelection(ctx context.Context, arg UpsertSelectionParams) error {
	_, err := q.db.Exec(ctx, upsertSelection, arg.SessionID, arg.PhotoID, arg.Note)
	return err
}
