// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_photos.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getReadyClientPhotoProofKey = `-- name: GetReadyClientPhotoProofKey :one
SELECT
  proof_key
FROM session_photos
WHERE id = $1
  AND session_id = $2
  AND status = 'ready'
  AND proof_key IS NOT NULL
`

type GetReadyClientPhotoProofKeyParams struct {
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) GetReadyClientPhotoProofKey(ctx context.Context, arg GetReadyClientPhotoProofKeyParams) (*string, error) {
	row := q.db.QueryRow(ctx, getReadyClientPhotoProofKey, arg.PhotoID, arg.SessionID)
	var proof_key *string
	err := row.Scan(&proof_key)
	return proof_key, err
}

const getSessionPhotoByIDAndSessionID = `-- name: GetSessionPhotoByIDAndSessionID :one
SELECT
    id,
    session_id,
    source_key,
    status,
    source_size_bytes,
    watermark_seed
FROM session_photos
WHERE id = $1
AND session_id = $2
`

type GetSessionPhotoByIDAndSessionIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

type GetSessionPhotoByIDAndSessionIDRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	SessionID       uuid.UUID `db:"session_id" json:"session_id"`
	SourceKey       string    `db:"source_key" json:"source_key"`
	Status          string    `db:"status" json:"status"`
	SourceSizeBytes int64     `db:"source_size_bytes" json:"source_size_bytes"`
	WatermarkSeed   int32     `db:"watermark_seed" json:"watermark_seed"`
}

func (q *Queries) GetSessionPhotoByIDAndSessionID(ctx context.Context, arg GetSessionPhotoByIDAndSessionIDParams) (GetSessionPhotoByIDAndSessionIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionPhotoByIDAndSessionID, arg.ID, arg.SessionID)
	var i GetSessionPhotoByIDAndSessionIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SourceKey,
		&i.Status,
		&i.SourceSizeBytes,
		&i.WatermarkSeed,
	)
	return i, err
}

const getSessionPhotoStats = `-- name: GetSessionPhotoStats :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(*) FILTER (WHERE status = 'pending_upload')::bigint AS pending_upload_count,
    COUNT(*) FILTER (WHERE status = 'uploaded')::bigint       AS uploaded_count,
    COUNT(*) FILTER (WHERE status = 'processing')::bigint     AS processing_count,
    COUNT(*) FILTER (WHERE status = 'ready')::bigint          AS ready_count,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint         AS failed_count
FROM session_photos
WHERE session_id = $1
`

type GetSessionPhotoStatsRow struct {
	TotalCount         int64 `db:"total_count" json:"total_count"`
	PendingUploadCount int64 `db:"pending_upload_count" json:"pending_upload_count"`
	UploadedCount      int64 `db:"uploaded_count" json:"uploaded_count"`
	ProcessingCount    int64 `db:"processing_count" json:"processing_count"`
	ReadyCount         int64 `db:"ready_count" json:"ready_count"`
	FailedCount        int64 `db:"failed_count" json:"failed_count"`
}

func (q *Queries) GetSessionPhotoStats(ctx context.Context, sessionID uuid.UUID) (GetSessionPhotoStatsRow, error) {
	row := q.db.QueryRow(ctx, getSessionPhotoStats, sessionID)
	var i GetSessionPhotoStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.PendingUploadCount,
		&i.UploadedCount,
		&i.ProcessingCount,
		&i.ReadyCount,
		&i.FailedCount,
	)
	return i, err
}

const isReadySessionPhoto = `-- name: IsReadySessionPhoto :one
SELECT EXISTS (
    SELECT 1
    FROM session_photos
    WHERE id = $1
      AND session_id = $2
      AND status = 'ready'
) AS ok
`

type IsReadySessionPhotoParams struct {
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) IsReadySessionPhoto(ctx context.Context, arg IsReadySessionPhotoParams) (bool, error) {
	row := q.db.QueryRow(ctx, isReadySessionPhoto, arg.PhotoID, arg.SessionID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const listReadyClientSessionPhotos = `-- name: ListReadyClientSessionPhotos :many
SELECT
  sp.id AS photo_id,
  sp.thumb_key,
  s.note,
  (CASE WHEN s.photo_id IS NOT NULL THEN TRUE ELSE FALSE END)::boolean AS selected
FROM session_photos sp
LEFT JOIN selections s
  ON s.session_id = sp.session_id
 AND s.photo_id = sp.id
WHERE sp.session_id = $1
  AND sp.status = 'ready'
ORDER BY sp.created_at, sp.id
LIMIT $3
OFFSET $2
`

type ListReadyClientSessionPhotosParams struct {
	SessionID   uuid.UUID `db:"session_id" json:"session_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

type ListReadyClientSessionPhotosRow struct {
	PhotoID  uuid.UUID `db:"photo_id" json:"photo_id"`
	ThumbKey *string   `db:"thumb_key" json:"thumb_key"`
	Note     *string   `db:"note" json:"note"`
	Selected bool      `db:"selected" json:"selected"`
}

func (q *Queries) ListReadyClientSessionPhotos(ctx context.Context, arg ListReadyClientSessionPhotosParams) ([]ListReadyClientSessionPhotosRow, error) {
	rows, err := q.db.Query(ctx, listReadyClientSessionPhotos, arg.SessionID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyClientSessionPhotosRow{}
	for rows.Next() {
		var i ListReadyClientSessionPhotosRow
		if err := rows.Scan(
			&i.PhotoID,
			&i.ThumbKey,
			&i.Note,
			&i.Selected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPhotoFailed = `-- name: MarkPhotoFailed :execrows
UPDATE session_photos
SET
status ='failed'
WHERE id = $1 
AND session_id = $2
AND status IN ('uploaded', 'processing')
`

type MarkPhotoFailedParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) MarkPhotoFailed(ctx context.Context, arg MarkPhotoFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPhotoFailed, arg.ID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPhotoProcessing = `-- name: MarkPhotoProcessing :execrows
UPDATE session_photos
SET
    status = 'processing'
WHERE id = $1
  AND session_id = $2
  AND status IN ('uploaded', 'processing')
`

type MarkPhotoProcessingParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) MarkPhotoProcessing(ctx context.Context, arg MarkPhotoProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPhotoProcessing, arg.ID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPhotoReady = `-- name: MarkPhotoReady :execrows
UPDATE session_photos
SET
status ='ready',
thumb_key = $1,
proof_key = $2 
WHERE id = $3 
AND session_id = $4
AND status = 'processing'
`

type MarkPhotoReadyParams struct {
	ThumbKey  *string   `db:"thumb_key" json:"thumb_key"`
	ProofKey  *string   `db:"proof_key" json:"proof_key"`
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) MarkPhotoReady(ctx context.Context, arg MarkPhotoReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPhotoReady,
		arg.ThumbKey,
		arg.ProofKey,
		arg.ID,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionPhotoUploaded = `-- name: MarkSessionPhotoUploaded :execrows
UPDATE session_photos
SET
  status = 'uploaded',
  source_size_bytes = $1
WHERE id = $2
AND session_id = $3
`

type MarkSessionPhotoUploadedParams struct {
	SourceSizeBytes int64     `db:"source_size_bytes" json:"source_size_bytes"`
	ID              uuid.UUID `db:"id" json:"id"`
	SessionID       uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) MarkSessionPhotoUploaded(ctx context.Context, arg MarkSessionPhotoUploadedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionPhotoUploaded, arg.SourceSizeBytes, arg.ID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
