// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_access.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSessionAccess = `-- name: InsertSessionAccess :one
INSERT INTO session_access (
  id,
  session_id,
  code_hmac,
  token_hmac
) VALUES (
$1,
$2,
$3,
$4
)
RETURNING
  id,
  created_at
`

type InsertSessionAccessParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	CodeHmac  string    `db:"code_hmac" json:"code_hmac"`
	TokenHmac string    `db:"token_hmac" json:"token_hmac"`
}

type InsertSessionAccessRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertSessionAccess(ctx context.Context, arg InsertSessionAccessParams) (InsertSessionAccessRow, error) {
	row := q.db.QueryRow(ctx, insertSessionAccess,
		arg.ID,
		arg.SessionID,
		arg.CodeHmac,
		arg.TokenHmac,
	)
	var i InsertSessionAccessRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const revokeSessionAccess = `-- name: RevokeSessionAccess :many
UPDATE session_access
SET revoked_at = now()
WHERE session_id = $1
AND revoked_at IS NULL
RETURNING
  id,
  session_id,
  created_at,
  revoked_at,
  last_used_at
`

type RevokeSessionAccessRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	SessionID  uuid.UUID  `db:"session_id" json:"session_id"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	RevokedAt  *time.Time `db:"revoked_at" json:"revoked_at"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) RevokeSessionAccess(ctx context.Context, sessionID uuid.UUID) ([]RevokeSessionAccessRow, error) {
	rows, err := q.db.Query(ctx, revokeSessionAccess, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeSessionAccessRow{}
	for rows.Next() {
		var i RevokeSessionAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
