// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_access.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getActiveClientSessionAccessByID = `-- name: GetActiveClientSessionAccessByID :one
SELECT
  id,
  session_id
FROM session_access
WHERE id = $1
AND revoked_at IS NULL
`

type GetActiveClientSessionAccessByIDRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) GetActiveClientSessionAccessByID(ctx context.Context, id uuid.UUID) (GetActiveClientSessionAccessByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveClientSessionAccessByID, id)
	var i GetActiveClientSessionAccessByIDRow
	err := row.Scan(&i.ID, &i.SessionID)
	return i, err
}

const getClientSessionByCodeHMAC = `-- name: GetClientSessionByCodeHMAC :one
SELECT 
  sessions.id,
  sessions.status,
  sessions.base_price_cents,
  sessions.included_count,
  sessions.extra_price_cents,
  sessions.min_select_count,
  sessions.currency,
  sessions.payment_mode,
  sessions.title
FROM session_access
JOIN sessions ON session_access.session_id = sessions.id
WHERE session_access.code_hmac = $1
AND session_access.revoked_at IS NULL
`

type GetClientSessionByCodeHMACRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Status          string    `db:"status" json:"status"`
	BasePriceCents  int32     `db:"base_price_cents" json:"base_price_cents"`
	IncludedCount   int32     `db:"included_count" json:"included_count"`
	ExtraPriceCents int32     `db:"extra_price_cents" json:"extra_price_cents"`
	MinSelectCount  int32     `db:"min_select_count" json:"min_select_count"`
	Currency        string    `db:"currency" json:"currency"`
	PaymentMode     string    `db:"payment_mode" json:"payment_mode"`
	Title           string    `db:"title" json:"title"`
}

func (q *Queries) GetClientSessionByCodeHMAC(ctx context.Context, codeHmac string) (GetClientSessionByCodeHMACRow, error) {
	row := q.db.QueryRow(ctx, getClientSessionByCodeHMAC, codeHmac)
	var i GetClientSessionByCodeHMACRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.BasePriceCents,
		&i.IncludedCount,
		&i.ExtraPriceCents,
		&i.MinSelectCount,
		&i.Currency,
		&i.PaymentMode,
		&i.Title,
	)
	return i, err
}

const getClientSessionByTokenHMAC = `-- name: GetClientSessionByTokenHMAC :one
SELECT 
  sessions.id,
  sessions.status,
  sessions.base_price_cents,
  sessions.included_count,
  sessions.extra_price_cents,
  sessions.min_select_count,
  sessions.currency,
  sessions.payment_mode,
  sessions.title
FROM session_access
JOIN sessions ON session_access.session_id = sessions.id
WHERE session_access.token_hmac = $1
AND session_access.revoked_at IS NULL
`

type GetClientSessionByTokenHMACRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Status          string    `db:"status" json:"status"`
	BasePriceCents  int32     `db:"base_price_cents" json:"base_price_cents"`
	IncludedCount   int32     `db:"included_count" json:"included_count"`
	ExtraPriceCents int32     `db:"extra_price_cents" json:"extra_price_cents"`
	MinSelectCount  int32     `db:"min_select_count" json:"min_select_count"`
	Currency        string    `db:"currency" json:"currency"`
	PaymentMode     string    `db:"payment_mode" json:"payment_mode"`
	Title           string    `db:"title" json:"title"`
}

func (q *Queries) GetClientSessionByTokenHMAC(ctx context.Context, tokenHmac string) (GetClientSessionByTokenHMACRow, error) {
	row := q.db.QueryRow(ctx, getClientSessionByTokenHMAC, tokenHmac)
	var i GetClientSessionByTokenHMACRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.BasePriceCents,
		&i.IncludedCount,
		&i.ExtraPriceCents,
		&i.MinSelectCount,
		&i.Currency,
		&i.PaymentMode,
		&i.Title,
	)
	return i, err
}

const insertSessionAccess = `-- name: InsertSessionAccess :one
INSERT INTO session_access (
  id,
  session_id,
  code_hmac,
  token_hmac
) VALUES (
$1,
$2,
$3,
$4
)
RETURNING
  id,
  created_at
`

type InsertSessionAccessParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	CodeHmac  string    `db:"code_hmac" json:"code_hmac"`
	TokenHmac string    `db:"token_hmac" json:"token_hmac"`
}

type InsertSessionAccessRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertSessionAccess(ctx context.Context, arg InsertSessionAccessParams) (InsertSessionAccessRow, error) {
	row := q.db.QueryRow(ctx, insertSessionAccess,
		arg.ID,
		arg.SessionID,
		arg.CodeHmac,
		arg.TokenHmac,
	)
	var i InsertSessionAccessRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const revokeSessionAccess = `-- name: RevokeSessionAccess :many
UPDATE session_access
SET revoked_at = now()
WHERE session_id = $1
AND revoked_at IS NULL
RETURNING
  id,
  session_id,
  created_at,
  revoked_at,
  last_used_at
`

type RevokeSessionAccessRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	SessionID  uuid.UUID  `db:"session_id" json:"session_id"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	RevokedAt  *time.Time `db:"revoked_at" json:"revoked_at"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) RevokeSessionAccess(ctx context.Context, sessionID uuid.UUID) ([]RevokeSessionAccessRow, error) {
	rows, err := q.db.Query(ctx, revokeSessionAccess, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeSessionAccessRow{}
	for rows.Next() {
		var i RevokeSessionAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
