// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_photos.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getSessionPhotoByIDAndSessionID = `-- name: GetSessionPhotoByIDAndSessionID :one
SELECT
    id,
    session_id,
    source_key,
    status,
    source_size_bytes
FROM session_photos
WHERE id = $1
AND session_id = $2
`

type GetSessionPhotoByIDAndSessionIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
}

type GetSessionPhotoByIDAndSessionIDRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	SessionID       uuid.UUID `db:"session_id" json:"session_id"`
	SourceKey       string    `db:"source_key" json:"source_key"`
	Status          string    `db:"status" json:"status"`
	SourceSizeBytes int64     `db:"source_size_bytes" json:"source_size_bytes"`
}

func (q *Queries) GetSessionPhotoByIDAndSessionID(ctx context.Context, arg GetSessionPhotoByIDAndSessionIDParams) (GetSessionPhotoByIDAndSessionIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionPhotoByIDAndSessionID, arg.ID, arg.SessionID)
	var i GetSessionPhotoByIDAndSessionIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SourceKey,
		&i.Status,
		&i.SourceSizeBytes,
	)
	return i, err
}

const markSessionPhotoUploaded = `-- name: MarkSessionPhotoUploaded :execrows
UPDATE session_photos
SET
  status = 'uploaded',
  source_size_bytes = $1
WHERE id = $2
AND session_id = $3
`

type MarkSessionPhotoUploadedParams struct {
	SourceSizeBytes int64     `db:"source_size_bytes" json:"source_size_bytes"`
	ID              uuid.UUID `db:"id" json:"id"`
	SessionID       uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) MarkSessionPhotoUploaded(ctx context.Context, arg MarkSessionPhotoUploadedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionPhotoUploaded, arg.SourceSizeBytes, arg.ID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
