// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getSessionOwnerByID = `-- name: GetSessionOwnerByID :one
SELECT
    id,
    photographer_id
FROM sessions
WHERE id = $1
`

type GetSessionOwnerByIDRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

func (q *Queries) GetSessionOwnerByID(ctx context.Context, id uuid.UUID) (GetSessionOwnerByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionOwnerByID, id)
	var i GetSessionOwnerByIDRow
	err := row.Scan(&i.ID, &i.PhotographerID)
	return i, err
}
