// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeSession = `-- name: CloseSession :one
UPDATE sessions
SET
  status = 'closed',
  closed_at = CURRENT_TIMESTAMP,
  delete_after = CURRENT_TIMESTAMP + INTERVAL '90 days'
WHERE id = $1
RETURNING
  id,
  title,
  status,
  closed_at,
  delete_after
`

type CloseSessionRow struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Title       string     `db:"title" json:"title"`
	Status      string     `db:"status" json:"status"`
	ClosedAt    *time.Time `db:"closed_at" json:"closed_at"`
	DeleteAfter *time.Time `db:"delete_after" json:"delete_after"`
}

func (q *Queries) CloseSession(ctx context.Context, id uuid.UUID) (CloseSessionRow, error) {
	row := q.db.QueryRow(ctx, closeSession, id)
	var i CloseSessionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.ClosedAt,
		&i.DeleteAfter,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT 
  id,
  photographer_id,
  title,
  client_email,
  status,
  base_price_cents,
  included_count,
  extra_price_cents,
  min_select_count,
  currency,
  payment_mode,
  created_at,
  updated_at,
  closed_at,
  delete_after
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.ClientEmail,
		&i.Status,
		&i.BasePriceCents,
		&i.IncludedCount,
		&i.ExtraPriceCents,
		&i.MinSelectCount,
		&i.Currency,
		&i.PaymentMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeleteAfter,
	)
	return i, err
}

const getSessionOwnerByID = `-- name: GetSessionOwnerByID :one
SELECT
    id,
    photographer_id
FROM sessions
WHERE id = $1
`

type GetSessionOwnerByIDRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
}

func (q *Queries) GetSessionOwnerByID(ctx context.Context, id uuid.UUID) (GetSessionOwnerByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionOwnerByID, id)
	var i GetSessionOwnerByIDRow
	err := row.Scan(&i.ID, &i.PhotographerID)
	return i, err
}

const getSessionStatusForUpdate = `-- name: GetSessionStatusForUpdate :one
SELECT
  id,
  status
FROM sessions
WHERE id = $1
FOR UPDATE
`

type GetSessionStatusForUpdateRow struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) GetSessionStatusForUpdate(ctx context.Context, id uuid.UUID) (GetSessionStatusForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSessionStatusForUpdate, id)
	var i GetSessionStatusForUpdateRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getSessions = `-- name: GetSessions :many
SELECT 
  id,
  photographer_id,
  title,
  client_email,
  status,
  base_price_cents,
  included_count,
  extra_price_cents,
  min_select_count,
  currency,
  payment_mode,
  created_at,
  updated_at,
  closed_at,
  delete_after
FROM sessions
WHERE photographer_id = $1
ORDER BY created_at DESC
LIMIT 200
OFFSET $2
`

type GetSessionsParams struct {
	PhotographerID uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Offset         int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetSessions(ctx context.Context, arg GetSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessions, arg.PhotographerID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Title,
			&i.ClientEmail,
			&i.Status,
			&i.BasePriceCents,
			&i.IncludedCount,
			&i.ExtraPriceCents,
			&i.MinSelectCount,
			&i.Currency,
			&i.PaymentMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeleteAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
  id,
  photographer_id,
  title,
  client_email,
  base_price_cents,
  included_count,
  extra_price_cents,
  min_select_count,
  currency,
  payment_mode

) VALUES(
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10
)
RETURNING 
  id,
  status
`

type InsertSessionParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	PhotographerID  uuid.UUID `db:"photographer_id" json:"photographer_id"`
	Title           string    `db:"title" json:"title"`
	ClientEmail     *string   `db:"client_email" json:"client_email"`
	BasePriceCents  int32     `db:"base_price_cents" json:"base_price_cents"`
	IncludedCount   int32     `db:"included_count" json:"included_count"`
	ExtraPriceCents int32     `db:"extra_price_cents" json:"extra_price_cents"`
	MinSelectCount  int32     `db:"min_select_count" json:"min_select_count"`
	Currency        string    `db:"currency" json:"currency"`
	PaymentMode     string    `db:"payment_mode" json:"payment_mode"`
}

type InsertSessionRow struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.PhotographerID,
		arg.Title,
		arg.ClientEmail,
		arg.BasePriceCents,
		arg.IncludedCount,
		arg.ExtraPriceCents,
		arg.MinSelectCount,
		arg.Currency,
		arg.PaymentMode,
	)
	var i InsertSessionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const isSelectedSessionPhoto = `-- name: IsSelectedSessionPhoto :one
SELECT EXISTS (
  SELECT 1
  FROM selections
  WHERE session_id = $1
    AND photo_id = $2
) AS ok
`

type IsSelectedSessionPhotoParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	PhotoID   uuid.UUID `db:"photo_id" json:"photo_id"`
}

func (q *Queries) IsSelectedSessionPhoto(ctx context.Context, arg IsSelectedSessionPhotoParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSelectedSessionPhoto, arg.SessionID, arg.PhotoID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const markSessionEditing = `-- name: MarkSessionEditing :execrows
UPDATE sessions
SET
  status = 'editing',
  updated_at = now()
WHERE id = $1
  AND status = 'waiting_for_payment'
`

func (q *Queries) MarkSessionEditing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionEditing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionFailed = `-- name: MarkSessionFailed :execrows
UPDATE sessions
SET
    status = 'failed',
    updated_at = now()
WHERE id = $1
  AND status IN ('draft', 'processing')
`

func (q *Queries) MarkSessionFailed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionProcessing = `-- name: MarkSessionProcessing :execrows
UPDATE sessions
SET
    status = 'processing',
    updated_at = now()
WHERE id = $1
  AND status = 'draft'
`

func (q *Queries) MarkSessionProcessing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionSelecting = `-- name: MarkSessionSelecting :execrows
UPDATE sessions
SET
    status = 'selecting',
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
`

func (q *Queries) MarkSessionSelecting(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionSelecting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
