// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_access.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSessionAccess = `-- name: InsertSessionAccess :one
INSERT INTO session_access (
  id,
  session_id,
  code_hmac,
  token_hmac
) VALUES (
$1,
$2,
$3,
$4
)
RETURNING
  id,
  created_at
`

type InsertSessionAccessParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	CodeHmac  string    `db:"code_hmac" json:"code_hmac"`
	TokenHmac string    `db:"token_hmac" json:"token_hmac"`
}

type InsertSessionAccessRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertSessionAccess(ctx context.Context, arg InsertSessionAccessParams) (InsertSessionAccessRow, error) {
	row := q.db.QueryRow(ctx, insertSessionAccess,
		arg.ID,
		arg.SessionID,
		arg.CodeHmac,
		arg.TokenHmac,
	)
	var i InsertSessionAccessRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
