// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const upsertUserFromGoogle = `-- name: UpsertUserFromGoogle :one
INSERT INTO users (
    id,
    google_sub,
    email,
    name,
    avatar_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5, '')
)
ON CONFLICT (google_sub) DO UPDATE
SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url
RETURNING
    id,
    google_sub,
    email,
    name,
    avatar_url,
    created_at
`

type UpsertUserFromGoogleParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	GoogleSub string      `db:"google_sub" json:"google_sub"`
	Email     string      `db:"email" json:"email"`
	Name      string      `db:"name" json:"name"`
	AvatarUrl interface{} `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpsertUserFromGoogle(ctx context.Context, arg UpsertUserFromGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromGoogle,
		arg.ID,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
